### ISSUE TITLE
rewire electrical system for using tether instead of battery

### ISSUE THREAD

**Issue by cTurtle98** [Carter90/cabrillo_rov#17]
- [x] remove xt60 splitters
- [x] remove xt60 connectors from speed controllers
- [x] build power distribution bus bar
- [x] rewire up speed controllers
- [x] reconnect raspberry pi
- [x] crimp tether cable into solar connector
- [x] pot tether cables into penetrator
- [x] pot box to box cat6 into penetrator
- [x] decide where to mount lower box
- [x] build proto board for claw cables
- [x] pot claw cables into penetrators

**Comment by cabrillorobotics** [comment]
completed
