### ISSUE TITLE
fix controler.py

### ISSUE THREAD

**Issue by cTurtle98** [Carter90/cabrillo_rov#21]
i tried to reverse the controls so the trigger closes the claw and the bumper opens the claw and i broke the controller.py in the process

need to get controller.py working again with the desired control schema

**Comment by Carter90** [comment]
`controller.py`
These lines
https://github.com/cabrillorobotics/cabrillo_rov/blob/ff553610f16d8eed41a723a48767a95ff3c74255/src/control/src/controller.py#L61
https://github.com/cabrillorobotics/cabrillo_rov/blob/ff553610f16d8eed41a723a48767a95ff3c74255/src/control/src/controller.py#L65

**Comment by Carter90** [comment]
Resolved 53ec3dd6628fe455f14e032775d3150b07043173

**Comment by Carter90** [comment]
@cTurtle98 It would be good for you to verify the fix on the physical rov

**Comment by cTurtle98** [comment]
the controls are confirmed the way I want. trigger closes and bumper opens
